# Generated by Django 5.1.2 on 2024-11-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_materia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_professor', models.CharField(max_length=100)),
                ('fk_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='dever.escola')),
            ],
        ),
        migrations.CreateModel(
            name='DeverDeCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('fk_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deveres', to='dever.escola')),
                ('fk_livro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dever.livro')),
                ('fk_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dever.materia')),
                ('fk_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deveres', to='dever.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('fk_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='dever.escola')),
                ('fk_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='dever.professor')),
            ],
        ),
    ]
