# Generated by Django 5.1.3 on 2024-11-14 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dever', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deverdecasa',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dever_escola', to='dever.escola'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_escola', to='dever.escola'),
        ),
        migrations.AddField(
            model_name='deverdecasa',
            name='fk_livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dever_livro', to='dever.livro'),
        ),
        migrations.AddField(
            model_name='livro',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_materias', to='dever.materia'),
        ),
        migrations.AddField(
            model_name='deverdecasa',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dever_materia', to='dever.materia'),
        ),
        migrations.AddField(
            model_name='professor',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores_escola', to='dever.escola'),
        ),
        migrations.AddField(
            model_name='professor',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_materias', to='dever.materia'),
        ),
        migrations.AddField(
            model_name='deverdecasa',
            name='fk_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dever_professor', to='dever.professor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma_escola', to='dever.escola'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='fk_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_turma', to='dever.turma'),
        ),
    ]
