# Generated by Django 5.1.3 on 2024-11-12 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dever', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_livro', to='dever.materia'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_professor', to='dever.materia'),
        ),
    ]
