# Generated by Django 5.1.3 on 2025-04-11 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dever', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='fk_escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='livro_escola', to='dever.escola', verbose_name='Nome da escola'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_escola', to='dever.escola', verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='fk_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_turma', to='dever.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_user', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='nome_aluno',
            field=models.CharField(max_length=100, verbose_name='Nome do aluno'),
        ),
        migrations.AlterField(
            model_name='deverdecasa',
            name='data_entrega',
            field=models.DateField(verbose_name='Data da entrega'),
        ),
        migrations.AlterField(
            model_name='deverdecasa',
            name='dever',
            field=models.TextField(verbose_name='Dever de casa'),
        ),
        migrations.AlterField(
            model_name='deverdecasa',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dever_escola', to='dever.escola', verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='deverdecasa',
            name='fk_livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dever_livro', to='dever.livro', verbose_name='Livro'),
        ),
        migrations.AlterField(
            model_name='deverdecasa',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dever_materia', to='dever.materia', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='deverdecasa',
            name='fk_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dever_professor', to='dever.professor', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome_escola',
            field=models.CharField(max_length=100, verbose_name='Nome da escola'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_materia', to='dever.materia', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome_livro',
            field=models.CharField(max_length=100, verbose_name='Nome do livro'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome_materia',
            field=models.CharField(max_length=100, verbose_name='Nome da matéria'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores_escola', to='dever.escola', verbose_name='Nome da escola'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_materias', to='dever.materia', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome_professor',
            field=models.CharField(max_length=100, verbose_name='Nome do Professor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma_escola', to='dever.escola', verbose_name='Nome da escola'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma',
            field=models.CharField(max_length=100, verbose_name='Nome da turma'),
        ),
    ]
